### ISSUE TITLE
[Bug] AutoCube crashes when launched from within Wine/Proton

### ISSUE THREAD

**Issue by some-username-here1** [The-Orange-Toolbox/AutoCube#1]
Currently, launching AutoCube from within Wine crashes. The cause of it is unknown, but AutoCube provides an output for the crash log as shown below (a image to text converter was used here, so apologies if there is any typos or errors):
```
The Orange Toolbox - AutoCube.exe (Sep 28 2021)

Launching game...
There is a problem with AutoCube
Please report issues here: https://github.com/The-Orange-Toolbox/AutoCube/issues

Traceback (most recent call last):
    File "psutil\_common.py", line 447, in wrapper
AttributeError: _cache

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
    File "__main__.py", line 49, in <module>
    File "buildcubemaps.py", line 13, in buildcubemaps
    File "valveexe\exe.py", line 66, in launch
    File "valveexe\utils.py", line 4, in find_process
    File "valveexe\utils.py", line 5, in <genexpr>
    File "psutil\___init__.py", line 617, in name
    File "psutil\_pswindows.py", line 750, in name
    File "psutil\_pswindows.py", line 681, in wrapper
    File "psutil\_pswindows.py", line 671, in convert_oserror
    File "psutil\_pswindows.py", line 679, in wrapper
    File "psutil\_common.py", line 450, in wrapper
    File "psutil\_pswindows.py", line 766, in exe
OSError: [WinError 87] Invalid parameter: '(originated from NtQuerySystem Information)'
Traceback (most recent call last):
    File "psutil\_common.py", line 447, in wrapper
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    File "__main__.py", line 49, in <module>
    File "buildcubemaps.py", line 13, in buildcubemaps File "valveexe\exe.py", line 66, in launch
    File "valveexe\utils.py", line 4, in find_process
    File "valveexe\utils.py", line 5, in <genexpr>
    File "psutil\___init__.py", line 617, in name
    File "psutil\_pswindows.py", line 750, in name
    File "psutil\_pswindows.py", line 681, in wrapper
    File "psutil\_pswindows.py", line 671, in convert_oserror
    File "psutil\_pswindows.py", line 679, in wrapper
    File "psutil\_common.py", line 450, in wrapper
    File "psutil\_pswindows.py", line 766, in exe
OSError: [WinError 87] Invalid parameter: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    File "__main__.py", line 49, in <module>
    File "totcommon\executable.py", line 25, in exit__
    File "totcommon\reporter.py", line 18, in ___exit__
NameError: name 'exit' is not defined
[2320] Failed to execute script '__main__' due to unhandled exception!
Exception ignored in: <function ValveExe.___del__ at 0x0000000002C83670>
Traceback (most recent call last):
    File "valveexe\exe.py", line 155, in ___del__
AttributeError: logger
```

It would be nice if this program can work properly under Wine/Proton as one wouldn't need to go through the whole building cubemaps setup from in-game every recompile.

**Comment by maxdup** [comment]
Not gonna lie to you. While I love linux, I have very little hope that this is ever going to run through wine.
 
That said, I plan to revisit the project if I eventually drop CSGO support. It should allow me more freedom in how things are implemented but even then, Wine is unlikely to happen. I'll keep it in the back of my mind tho.

(a native binary for linux is not out of the question however, we'll see)

**Comment by some-username-here1** [comment]
There can't be two exe versions? One for source 1 games in general and another for csgo specifically. Like a base code with two forks that applies over said code, if there's general functions that don't work in csgo and vice versa.

**Comment by maxdup** [comment]
My current understanding is that csgo will stop existing and will be fully replaced by Counter Strike 2. That's why I was saying csgo support will be dropped eventually. Source 2 is a different beast and would require its own tools
